---
- name: Configure network interfaces
  hosts: all
  connection: network_cli
  gather_facts: no
  vars:
    ansible_user: vyos
    ansible_ssh_pass: vyos

  tasks:

    - name: get netbox json
      uri:
        url: http://192.168.56.103/api/ipam/ip-addresses/?device_id={{ device_id }}
        method: GET
        headers:
          content-type: 'aplication/json'
          Authorization: 'Token 40331d916c88aa9d5dfd1be41d1c8833e073594b'
        body_format: json
      register: host_info
      delegate_to: localhost
    
    # - debug:
    #     var: host_info.json.results
    
      
    - name: Configure network interfaces
      vyos_l3_interfaces:
        config:
          - name: "{{ item.interface.name }}"
            ipv4:
              - address: "{{ item.address }}"
        state: replaced
      with_items: "{{ host_info.json.results }}"